-- Insert roles if they don't exist
-- INSERT INTO roles (name) VALUES ('ROLE_CUSTOMER') ON CONFLICT (name) DO NOTHING;
-- INSERT INTO roles (name) VALUES ('ROLE_STAFF') ON CONFLICT (name) DO NOTHING;
-- INSERT INTO roles (name) VALUES ('ROLE_ADMIN') ON CONFLICT (name) DO NOTHING;
-- INSERT INTO roles (name) VALUES ('ROLE_WAITER') ON CONFLICT (name) DO NOTHING; 